name: Deploy to gh-pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Install Dependencies
        run: |
          npm i
          npm install -g html-minifier
          npm install -g clean-css-cli
          npm install -g uglify-js
          
      - name: Minify HTML, CSS, and JS files
        run: |
          while read -d $'\0' file; do
            rel_path=${file#./}
            min_path="dist/$rel_path"
            mkdir -p "$(dirname "$min_path")"

            case "$file" in
              *.html)
                html-minifier "$file" -o "$min_path" --collapse-whitespace --remove-comments
              ;;
              *.css)
                cleancss "$file" -o "$min_path" --compatibility "ie >= 11, Edge >= 12, Firefox >= 2, Chrome >= 4, Safari >= 3.1, Opera >= 15, iOS >= 3.2"
              ;;
              *.js)
                uglifyjs "$file" -o "$min_path" --compress drop_console --mangle --mangle-props
              ;;
            esac
          done < <(find . -type f -not -path "*node_modules/*" \( -name '*.html' -o -name '*.css' -o -name '*.js' \) -print0)

      - uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          branch: gh-pages
          folder: dist

