name: Main to gh-pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Create gh-pages branch if not exists
        run: | 
          git branch gh-pages || true
          git checkout gh-pages

      - name: Copy code to gh-pages branch
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git checkout gh-pages
          git merge main --no-edit
          git push origin gh-pages
